export const technicalDiagramLabels = {
  root: {
    architecture: {
      capture: 'Capture surfaces',
      sharedHelpers: 'Shared native helpers',
      translation: 'Shared translation flow',
      overlay: 'Overlay publication',
      persistence: 'Persistence handoff',
      languageMetadata: 'Language metadata',
    },
    pipeline: {
      capture: 'Capture source text',
      scopeReuse: 'Resolve scope and reuse',
      translation: 'Shared translation flow',
      overlay: 'Overlay publication',
      nativeMode: 'Native publication',
      swapMode: 'Swap publication',
    },
    translatorArchitecture: {
      sharedRuntime: 'Shared runtime',
      selection: 'Translator selection',
      orchestration: 'Request orchestration',
      persistenceHandoff: 'Persistence handoff',
      engineAdapters: 'Engine adapters',
      clientSetup: 'Provider client setup',
      payloadShape: 'Request payload shape',
      responseParsing: 'Response parsing',
    },
    nativeUiAndOverlays: {
      translationFinished: 'Translation finished',
      presentationMode: 'Presentation mode',
      overlayOnly: 'Overlay-only presentation',
      nativeMode: 'Native presentation',
      swapMode: 'Swap presentation',
    },
    cacheAndPersistence: {
      sourceOfTruth: 'Source of truth',
      reuseLayer: 'Reuse layer',
      visibleState: 'Visible state reuse',
      scopeRules: 'Scope rules',
    },
    diagnostics: {
      issueObserved: 'Issue observed',
      probe: 'Probe supported addon',
      classifyByStage: 'Classify by stage',
      capture: 'Capture issue',
      cachePersistence: 'Cache or persistence issue',
      overlay: 'Overlay issue',
      nativeMutation: 'Native mutation issue',
    },
    development: {
      scopedChange: 'Scoped change',
      docsValidation: 'Docs validation',
      pluginValidation: 'Plugin validation',
      pullRequest: 'Pull request',
      mergeToV4Series: 'Merge to v4-series',
    },
  },
};
