export const technicalDiagramLabels = {
  root: {
    architecture: {
      capture: 'Capture surfaces',
      sharedHelpers: 'Shared native helpers',
      translation: 'Shared translation flow',
      overlay: 'Overlay publication',
      persistence: 'Persistence handoff',
      languageMetadata: 'Language metadata',
    },
    pipeline: {
      capture: 'Capture source text',
      scopeReuse: 'Resolve scope and reuse',
      translation: 'Shared translation flow',
      overlay: 'Overlay publication',
      nativeMode: 'Native publication',
      swapMode: 'Swap publication',
    },
    translatorArchitecture: {
      sharedRuntime: 'Shared runtime',
      selection: 'Translator selection',
      orchestration: 'Request orchestration',
      persistenceHandoff: 'Persistence handoff',
      engineAdapters: 'Engine adapters',
      clientSetup: 'Provider client setup',
      payloadShape: 'Request payload shape',
      responseParsing: 'Response parsing',
    },
    nativeUiAndOverlays: {
      translationFinished: 'Translation finished',
      presentationMode: 'Presentation mode',
      overlayOnly: 'Overlay-only presentation',
      nativeMode: 'Native presentation',
      swapMode: 'Swap presentation',
    },
    cacheAndPersistence: {
      sourceOfTruth: 'Source of truth',
      reuseLayer: 'Reuse layer',
      visibleState: 'Visible state reuse',
      scopeRules: 'Scope rules',
    },
    diagnostics: {
      issueObserved: 'Issue observed',
      probe: 'Probe supported addon',
      classifyByStage: 'Classify by stage',
      capture: 'Capture issue',
      cachePersistence: 'Cache or persistence issue',
      overlay: 'Overlay issue',
      nativeMutation: 'Native mutation issue',
    },
    development: {
      scopedChange: 'Scoped change',
      docsValidation: 'Docs validation',
      pluginValidation: 'Plugin validation',
      pullRequest: 'Pull request',
      mergeToV4Series: 'Merge to v4-series',
    },
  },
  da: {
    architecture: {
      capture: 'Indfang kildetekst',
      sharedHelpers: 'Delte native hjælpere',
      translation: 'Delt oversættelsesflow',
      overlay: 'Overlay-publicering',
      persistence: 'Persistensoverdragelse',
      languageMetadata: 'Sprogmetadata',
    },
    pipeline: {
      capture: 'Indfang kildetekst',
      scopeReuse: 'Afgør scope og genbrug',
      translation: 'Oversæt resultat',
      overlay: 'Overlay-publicering',
      nativeMode: 'Publicering i native-tilstand',
      swapMode: 'Publicering i swap-tilstand',
    },
    translatorArchitecture: {
      sharedRuntime: 'Delt runtime',
      selection: 'Valg af oversætter',
      orchestration: 'Anmodningsorkestrering',
      persistenceHandoff: 'Persistensoverdragelse',
      engineAdapters: 'Engine-adaptere',
      clientSetup: 'Opsætning af provider-klient',
      payloadShape: 'Form på request-payload',
      responseParsing: 'Parsing af response',
    },
    nativeUiAndOverlays: {
      translationFinished: 'Oversættelse fuldført',
      presentationMode: 'Præsentationstilstand',
      overlayOnly: 'Overlay-only-præsentation',
      nativeMode: 'Native-præsentation',
      swapMode: 'Swap-præsentation',
    },
    cacheAndPersistence: {
      sourceOfTruth: 'Sandhedskilde',
      reuseLayer: 'Genbrugslag',
      visibleState: 'Genbrug af synlig tilstand',
      scopeRules: 'Scope-regler',
    },
    diagnostics: {
      issueObserved: 'Problem observeret',
      probe: 'Undersøg understøttet addon',
      classifyByStage: 'Klassificér efter trin',
      capture: 'Capture-problem',
      cachePersistence: 'Cache- eller persistensproblem',
      overlay: 'Overlay-problem',
      nativeMutation: 'Native-mutationsproblem',
    },
    development: {
      scopedChange: 'Afgrænset ændring',
      docsValidation: 'Docs-validering',
      pluginValidation: 'Plugin-validering',
      pullRequest: 'Pull request',
      mergeToV4Series: 'Flet til v4-series',
    },
  },
  de: {
    architecture: {
      capture: 'Quelltext erfassen',
      sharedHelpers: 'Gemeinsame native-Helfer',
      translation: 'Gemeinsamer Übersetzungsfluss',
      overlay: 'Overlay-Veröffentlichung',
      persistence: 'Persistenzübergabe',
      languageMetadata: 'Sprachmetadaten',
    },
    pipeline: {
      capture: 'Quelltext erfassen',
      scopeReuse: 'Scope bestimmen und Wiederverwendung',
      translation: 'Ergebnis übersetzen',
      overlay: 'Overlay-Veröffentlichung',
      nativeMode: 'Native-Veröffentlichung',
      swapMode: 'Swap-Veröffentlichung',
    },
    translatorArchitecture: {
      sharedRuntime: 'Gemeinsame Runtime',
      selection: 'Übersetzerwahl',
      orchestration: 'Anfrage-Orchestrierung',
      persistenceHandoff: 'Persistenzübergabe',
      engineAdapters: 'Engine-Adapter',
      clientSetup: 'Provider-Client-Setup',
      payloadShape: 'Request-Payload-Form',
      responseParsing: 'Response-Parsing',
    },
    nativeUiAndOverlays: {
      translationFinished: 'Übersetzung abgeschlossen',
      presentationMode: 'Präsentationsmodus',
      overlayOnly: 'Overlay-only-Präsentation',
      nativeMode: 'Native-Präsentation',
      swapMode: 'Swap-Präsentation',
    },
    cacheAndPersistence: {
      sourceOfTruth: 'Quelle der Wahrheit',
      reuseLayer: 'Wiederverwendungsebene',
      visibleState: 'Wiederverwendung sichtbaren Zustands',
      scopeRules: 'Scope-Regeln',
    },
    diagnostics: {
      issueObserved: 'Problem beobachtet',
      probe: 'Unterstütztes Addon prüfen',
      classifyByStage: 'Nach Stufe einordnen',
      capture: 'Capture-Problem',
      cachePersistence: 'Cache- oder Persistenzproblem',
      overlay: 'Overlay-Problem',
      nativeMutation: 'Native-Mutationsproblem',
    },
    development: {
      scopedChange: 'Begrenzte Änderung',
      docsValidation: 'Docs-Validierung',
      pluginValidation: 'Plugin-Validierung',
      pullRequest: 'Pull Request',
      mergeToV4Series: 'In v4-series mergen',
    },
  },
  el: {
    architecture: {
      capture: 'Καταγραφή κειμένου πηγής',
      sharedHelpers: 'Κοινά native βοηθήματα',
      translation: 'Κοινή ροή μετάφρασης',
      overlay: 'Δημοσίευση overlay',
      persistence: 'Παράδοση στην persistence',
      languageMetadata: 'Μεταδεδομένα γλώσσας',
    },
    pipeline: {
      capture: 'Καταγραφή κειμένου πηγής',
      scopeReuse: 'Επίλυση scope και επαναχρήσης',
      translation: 'Μετάφραση αποτελέσματος',
      overlay: 'Δημοσίευση overlay',
      nativeMode: 'Δημοσίευση native',
      swapMode: 'Δημοσίευση swap',
    },
    translatorArchitecture: {
      sharedRuntime: 'Κοινό runtime',
      selection: 'Επιλογή μεταφραστή',
      orchestration: 'Ενορχήστρωση αιτημάτων',
      persistenceHandoff: 'Παράδοση στην persistence',
      engineAdapters: 'Προσαρμογείς engine',
      clientSetup: 'Ρύθμιση client του provider',
      payloadShape: 'Σχήμα request payload',
      responseParsing: 'Ανάλυση response',
    },
    nativeUiAndOverlays: {
      translationFinished: 'Η μετάφραση ολοκληρώθηκε',
      presentationMode: 'Τρόπος παρουσίασης',
      overlayOnly: 'Παρουσίαση μόνο overlay',
      nativeMode: 'Παρουσίαση native',
      swapMode: 'Παρουσίαση swap',
    },
    cacheAndPersistence: {
      sourceOfTruth: 'Πηγή αλήθειας',
      reuseLayer: 'Επίπεδο επαναχρήσης',
      visibleState: 'Επαναχρήση ορατής κατάστασης',
      scopeRules: 'Κανόνες scope',
    },
    diagnostics: {
      issueObserved: 'Παρατηρήθηκε πρόβλημα',
      probe: 'Έλεγχος υποστηριζόμενου addon',
      classifyByStage: 'Ταξινόμηση ανά στάδιο',
      capture: 'Πρόβλημα capture',
      cachePersistence: 'Πρόβλημα cache ή persistence',
      overlay: 'Πρόβλημα overlay',
      nativeMutation: 'Πρόβλημα native mutation',
    },
    development: {
      scopedChange: 'Περιορισμένη αλλαγή',
      docsValidation: 'Έλεγχος docs',
      pluginValidation: 'Έλεγχος plugin',
      pullRequest: 'Pull request',
      mergeToV4Series: 'Merge στο v4-series',
    },
  },
  es: {
    architecture: {
      capture: 'Capturar texto de origen',
      sharedHelpers: 'Ayudantes native compartidos',
      translation: 'Flujo de traducción compartido',
      overlay: 'Publicación en overlay',
      persistence: 'Transferencia a persistencia',
      languageMetadata: 'Metadatos de idioma',
    },
    pipeline: {
      capture: 'Capturar texto de origen',
      scopeReuse: 'Resolver scope y reutilización',
      translation: 'Traducir resultado',
      overlay: 'Publicación en overlay',
      nativeMode: 'Publicación native',
      swapMode: 'Publicación swap',
    },
    translatorArchitecture: {
      sharedRuntime: 'Runtime compartido',
      selection: 'Selección de traductor',
      orchestration: 'Orquestación de solicitudes',
      persistenceHandoff: 'Transferencia a persistencia',
      engineAdapters: 'Adaptadores de engine',
      clientSetup: 'Configuración del cliente del provider',
      payloadShape: 'Forma del payload de la solicitud',
      responseParsing: 'Análisis de la respuesta',
    },
    nativeUiAndOverlays: {
      translationFinished: 'Traducción completada',
      presentationMode: 'Modo de presentación',
      overlayOnly: 'Presentación solo overlay',
      nativeMode: 'Presentación native',
      swapMode: 'Presentación swap',
    },
    cacheAndPersistence: {
      sourceOfTruth: 'Fuente de verdad',
      reuseLayer: 'Capa de reutilización',
      visibleState: 'Reutilización del estado visible',
      scopeRules: 'Reglas de scope',
    },
    diagnostics: {
      issueObserved: 'Problema observado',
      probe: 'Probar addon compatible',
      classifyByStage: 'Clasificar por etapa',
      capture: 'Problema de capture',
      cachePersistence: 'Problema de caché o persistencia',
      overlay: 'Problema de overlay',
      nativeMutation: 'Problema de native mutation',
    },
    development: {
      scopedChange: 'Cambio acotado',
      docsValidation: 'Validación de docs',
      pluginValidation: 'Validación del plugin',
      pullRequest: 'Pull request',
      mergeToV4Series: 'Merge a v4-series',
    },
  },
  eu: {
    architecture: {
      capture: 'Iturburu-testua hartu',
      sharedHelpers: 'native laguntzaile partekatuak',
      translation: 'Itzulpen-fluxu partekatua',
      overlay: 'Overlay argitalpena',
      persistence: 'Persistence eskualdaketa',
      languageMetadata: 'Hizkuntza-metadata',
    },
    pipeline: {
      capture: 'Iturburu-testua hartu',
      scopeReuse: 'Scope eta berrerabilpena ebatzi',
      translation: 'Emaitza itzuli',
      overlay: 'Overlay argitalpena',
      nativeMode: 'native argitalpena',
      swapMode: 'swap argitalpena',
    },
    translatorArchitecture: {
      sharedRuntime: 'runtime partekatua',
      selection: 'Itzultzaile-hautaketa',
      orchestration: 'Eskaeren orkestrazioa',
      persistenceHandoff: 'Persistence eskualdaketa',
      engineAdapters: 'engine egokigailuak',
      clientSetup: 'provider client konfigurazioa',
      payloadShape: 'Request payload forma',
      responseParsing: 'Response analisia',
    },
    nativeUiAndOverlays: {
      translationFinished: 'Itzulpena amaituta',
      presentationMode: 'Aurkezpen-modua',
      overlayOnly: 'overlay-only aurkezpena',
      nativeMode: 'native aurkezpena',
      swapMode: 'swap aurkezpena',
    },
    cacheAndPersistence: {
      sourceOfTruth: 'Egiaren iturria',
      reuseLayer: 'Berrerabilpen-geruza',
      visibleState: 'Ikusgai egoeraren berrerabilpena',
      scopeRules: 'Scope arauak',
    },
    diagnostics: {
      issueObserved: 'Arazoa ikusi da',
      probe: 'Onartutako addon-a aztertu',
      classifyByStage: 'Sailkatu etaparen arabera',
      capture: 'Capture arazoa',
      cachePersistence: 'Cache edo persistence arazoa',
      overlay: 'Overlay arazoa',
      nativeMutation: 'Native mutation arazoa',
    },
    development: {
      scopedChange: 'Aldaketa mugatua',
      docsValidation: 'Docs balidazioa',
      pluginValidation: 'Plugin balidazioa',
      pullRequest: 'Pull request',
      mergeToV4Series: 'v4-series-era merge',
    },
  },
};
