//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Echoglossian.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Echoglossian.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseButtonLabel {
            get {
                return ResourceManager.GetString("CloseButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Configuration.
        /// </summary>
        internal static string ConfigTab1Name {
            get {
                return ResourceManager.GetString("ConfigTab1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toast configurations.
        /// </summary>
        internal static string ConfigTab2Name {
            get {
                return ResourceManager.GetString("ConfigTab2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echoglossian Configuration.
        /// </summary>
        internal static string ConfigWindowTitle {
            get {
                return ResourceManager.GetString("ConfigWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay font color:.
        /// </summary>
        internal static string FontColorSelectLabel {
            get {
                return ResourceManager.GetString("FontColorSelectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens Echoglossian config window.
        /// </summary>
        internal static string HelpMessage {
            get {
                return ResourceManager.GetString("HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?).
        /// </summary>
        internal static string HoverTooltipIndicator {
            get {
                return ResourceManager.GetString("HoverTooltipIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language could not be identified with an acceptable degree of certainty.
        /// </summary>
        internal static string LangIdentError {
            get {
                return ResourceManager.GetString("LangIdentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which language to translate to..
        /// </summary>
        internal static string LanguageSelectionTooltip {
            get {
                return ResourceManager.GetString("LanguageSelectionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language to translate to.
        /// </summary>
        internal static string LanguageSelectLabelText {
            get {
                return ResourceManager.GetString("LanguageSelectLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] milfilia {
            get {
                object obj = ResourceManager.GetObject("milfilia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] minfilia {
            get {
                object obj = ResourceManager.GetObject("minfilia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echoglossian.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle talk translation.
        /// </summary>
        internal static string Overlay_name {
            get {
                return ResourceManager.GetString("Overlay name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please adjust position if your overlay is not centered relative to the game&apos;s UI dialogue box..
        /// </summary>
        internal static string OverlayAdjustmentOrientations {
            get {
                return ResourceManager.GetString("OverlayAdjustmentOrientations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OverlayColorSelect.
        /// </summary>
        internal static string OverlayColorSelectName {
            get {
                return ResourceManager.GetString("OverlayColorSelectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to choose the overlay font color.
        /// </summary>
        internal static string OverlayFontColorOrientations {
            get {
                return ResourceManager.GetString("OverlayFontColorOrientations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay Font Size.
        /// </summary>
        internal static string OverlayFontSizeLabel {
            get {
                return ResourceManager.GetString("OverlayFontSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the font size for the dialogue text overlay.
        /// </summary>
        internal static string OverlayFontSizeOrientations {
            get {
                return ResourceManager.GetString("OverlayFontSizeOrientations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position adjustment.
        /// </summary>
        internal static string OverlayPositionAdjustmentLabel {
            get {
                return ResourceManager.GetString("OverlayPositionAdjustmentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display translated text overlay above game UI dialogue box instead of replacing its text with the translation.
        /// </summary>
        internal static string OverlayToggleLabel {
            get {
                return ResourceManager.GetString("OverlayToggleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust translation overlay width.
        /// </summary>
        internal static string OverlayWidthMultiplierOrientations {
            get {
                return ResourceManager.GetString("OverlayWidthMultiplierOrientations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialogue Width multiplier.
        /// </summary>
        internal static string OverlayWidthScrollLabel {
            get {
                return ResourceManager.GetString("OverlayWidthScrollLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy lokinmodar a Coffee.
        /// </summary>
        internal static string PatronButtonLabel {
            get {
                return ResourceManager.GetString("PatronButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pix {
            get {
                object obj = ResourceManager.GetObject("pix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIX qrcode.
        /// </summary>
        internal static string PixQrWindowLabel {
            get {
                return ResourceManager.GetString("PixQrWindowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan the QR code to send me a PIX - only valid in Brazil.
        /// </summary>
        internal static string PixText {
            get {
                return ResourceManager.GetString("PixText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan the QR code to send me a PIX - only valid in Brazil.
        /// </summary>
        internal static string QRCodeInstructionsText {
            get {
                return ResourceManager.GetString("QRCodeInstructionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Close Config Window.
        /// </summary>
        internal static string SaveCloseButtonLabel {
            get {
                return ResourceManager.GetString("SaveCloseButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send me a PIX donation!.
        /// </summary>
        internal static string SendPixButton {
            get {
                return ResourceManager.GetString("SendPixButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust toast translation overlay width.
        /// </summary>
        internal static string ToastOverlayWidthMultiplierOrientations {
            get {
                return ResourceManager.GetString("ToastOverlayWidthMultiplierOrientations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toast Overlay Width multiplier.
        /// </summary>
        internal static string ToastOverlayWidthScrollLabel {
            get {
                return ResourceManager.GetString("ToastOverlayWidthScrollLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate in-game Area name Toast Messages.
        /// </summary>
        internal static string TranslateAreaToastToggleText {
            get {
                return ResourceManager.GetString("TranslateAreaToastToggleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate battle talk.
        /// </summary>
        internal static string TransLateBattletalkToggle {
            get {
                return ResourceManager.GetString("TransLateBattletalkToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate in-game Class/Job change Toast Messages.
        /// </summary>
        internal static string TranslateClassChangeToastToggleText {
            get {
                return ResourceManager.GetString("TranslateClassChangeToastToggleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate in-game Error Toast Messages.
        /// </summary>
        internal static string TranslateErrorToastToggleText {
            get {
                return ResourceManager.GetString("TranslateErrorToastToggleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate NPCs names in dialogue boxes.
        /// </summary>
        internal static string TranslateNpcNamesToggle {
            get {
                return ResourceManager.GetString("TranslateNpcNamesToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate in-game Quest Toast Messages.
        /// </summary>
        internal static string TranslateQuestToastToggleText {
            get {
                return ResourceManager.GetString("TranslateQuestToastToggleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate in-game other miscellaneous Toast Messages.
        /// </summary>
        internal static string TranslateScreenInfoToastToggleText {
            get {
                return ResourceManager.GetString("TranslateScreenInfoToastToggleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate talk.
        /// </summary>
        internal static string TranslateTalkToggleLabel {
            get {
                return ResourceManager.GetString("TranslateTalkToggleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate in-game Toast Messages.
        /// </summary>
        internal static string TranslateToastToggleText {
            get {
                return ResourceManager.GetString("TranslateToastToggleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting translation....
        /// </summary>
        internal static string WaitingForTranslation {
            get {
                return ResourceManager.GetString("WaitingForTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select what kind of text you want to be translated.
        /// </summary>
        internal static string WhatToTranslateText {
            get {
                return ResourceManager.GetString("WhatToTranslateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which in-game Toast messages to translate.
        /// </summary>
        internal static string WhichToastsToTranslateText {
            get {
                return ResourceManager.GetString("WhichToastsToTranslateText", resourceCulture);
            }
        }
    }
}
