//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Echoglossian.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Echoglossian.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string ConfigTab1Name {
            get {
                return ResourceManager.GetString("ConfigTab1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echoglossian Configuration.
        /// </summary>
        internal static string ConfigWindowTitle {
            get {
                return ResourceManager.GetString("ConfigWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens Echoglossian config window.
        /// </summary>
        internal static string HelpMessage {
            get {
                return ResourceManager.GetString("HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?).
        /// </summary>
        internal static string HoverTooltipIndicator {
            get {
                return ResourceManager.GetString("HoverTooltipIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which language to translate to..
        /// </summary>
        internal static string LanguageSelectionTooltip {
            get {
                return ResourceManager.GetString("LanguageSelectionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language to translate to.
        /// </summary>
        internal static string LanguageSelectLabelText {
            get {
                return ResourceManager.GetString("LanguageSelectLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle talk translation.
        /// </summary>
        internal static string Overlay_name {
            get {
                return ResourceManager.GetString("Overlay name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please adjust position if your overlay is not centered relative to talk popup..
        /// </summary>
        internal static string OverlayAdjustmentOrientations {
            get {
                return ResourceManager.GetString("OverlayAdjustmentOrientations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position adjustment.
        /// </summary>
        internal static string OverlayPositionAdjustmentLabel {
            get {
                return ResourceManager.GetString("OverlayPositionAdjustmentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display translated text overlay above game UI dialogue box instead of replacing its text with the translation.
        /// </summary>
        internal static string OverlayToggleLabel {
            get {
                return ResourceManager.GetString("OverlayToggleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width multiplier.
        /// </summary>
        internal static string OverlayWidthScrollLabel {
            get {
                return ResourceManager.GetString("OverlayWidthScrollLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy lokinmodar a Coffee.
        /// </summary>
        internal static string PatronButtonLabel {
            get {
                return ResourceManager.GetString("PatronButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Close Config Window.
        /// </summary>
        internal static string SaveCloseButtonLabel {
            get {
                return ResourceManager.GetString("SaveCloseButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate battle talk.
        /// </summary>
        internal static string TransLateBattletalkToggle {
            get {
                return ResourceManager.GetString("TransLateBattletalkToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate talk.
        /// </summary>
        internal static string TranslateTalkToggleLabel {
            get {
                return ResourceManager.GetString("TranslateTalkToggleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting translation....
        /// </summary>
        internal static string WaitingForTranslation {
            get {
                return ResourceManager.GetString("WaitingForTranslation", resourceCulture);
            }
        }
    }
}
