// <auto-generated />
using System;
using Echoglossian.EFCoreSqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Echoglossian.EFCoreSqlite.Migrations
{
  [DbContext(typeof(EchoglossianDbContext))]
  [Migration("20250328012132_AddNullabilityToDBEntitiesColumns")]
  partial class AddNullabilityToDBEntitiesColumns
  {
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

      modelBuilder.Entity("EFCoreSqlite.Models.ActionTooltip", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("INTEGER");

            b.Property<DateTime?>("CreatedDate")
                      .HasColumnType("TEXT");

            b.Property<string>("GameVersion")
                      .HasColumnType("TEXT");

            b.Property<string>("OriginalActionTooltip")
                      .HasColumnType("TEXT");

            b.Property<string>("OriginalActionTooltipLang")
                      .HasColumnType("TEXT");

            b.Property<byte[]>("RowVersion")
                      .IsConcurrencyToken()
                      .ValueGeneratedOnAddOrUpdate()
                      .HasColumnType("BLOB");

            b.Property<string>("TranslatedActionTooltip")
                      .HasColumnType("TEXT");

            b.Property<int?>("TranslationEngine")
                      .HasColumnType("INTEGER");

            b.Property<string>("TranslationLang")
                      .HasColumnType("TEXT");

            b.Property<DateTime?>("UpdatedDate")
                      .HasColumnType("TEXT");

            b.HasKey("Id");

            b.ToTable("actiontooltips", (string)null);
          });

      modelBuilder.Entity("EFCoreSqlite.Models.BattleTalkMessage", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("INTEGER");

            b.Property<DateTime?>("CreatedDate")
                      .HasColumnType("TEXT");

            b.Property<string>("OriginalBattleTalkMessage")
                      .HasColumnType("TEXT");

            b.Property<string>("OriginalBattleTalkMessageLang")
                      .HasColumnType("TEXT");

            b.Property<string>("OriginalSenderNameLang")
                      .HasColumnType("TEXT");

            b.Property<byte[]>("RowVersion")
                      .IsConcurrencyToken()
                      .ValueGeneratedOnAddOrUpdate()
                      .HasColumnType("BLOB");

            b.Property<string>("SenderName")
                      .HasColumnType("TEXT");

            b.Property<string>("TranslatedBattleTalkMessage")
                      .HasColumnType("TEXT");

            b.Property<string>("TranslatedSenderName")
                      .HasColumnType("TEXT");

            b.Property<int?>("TranslationEngine")
                      .HasColumnType("INTEGER");

            b.Property<string>("TranslationLang")
                      .HasColumnType("TEXT");

            b.Property<DateTime?>("UpdatedDate")
                      .HasColumnType("TEXT");

            b.HasKey("Id");

            b.ToTable("battletalkmessages", (string)null);
          });

      modelBuilder.Entity("EFCoreSqlite.Models.GameWindow", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("INTEGER");

            b.Property<DateTime?>("CreatedDate")
                      .HasColumnType("TEXT");

            b.Property<string>("GameVersion")
                      .HasColumnType("TEXT");

            b.Property<string>("OriginalWindowStrings")
                      .HasColumnType("TEXT");

            b.Property<string>("OriginalWindowStringsLang")
                      .HasColumnType("TEXT");

            b.Property<byte[]>("RowVersion")
                      .IsConcurrencyToken()
                      .ValueGeneratedOnAddOrUpdate()
                      .HasColumnType("BLOB");

            b.Property<string>("TranslatedWindowStrings")
                      .HasColumnType("TEXT");

            b.Property<int?>("TranslationEngine")
                      .HasColumnType("INTEGER");

            b.Property<string>("TranslationLang")
                      .HasColumnType("TEXT");

            b.Property<DateTime?>("UpdatedDate")
                      .HasColumnType("TEXT");

            b.Property<string>("WindowAddonName")
                      .HasColumnType("TEXT");

            b.HasKey("Id");

            b.ToTable("gamewindows", (string)null);
          });

      modelBuilder.Entity("EFCoreSqlite.Models.ItemTooltip", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("INTEGER");

            b.Property<DateTime?>("CreatedDate")
                      .HasColumnType("TEXT");

            b.Property<string>("GameVersion")
                      .HasColumnType("TEXT");

            b.Property<string>("OriginalItemTooltip")
                      .HasColumnType("TEXT");

            b.Property<string>("OriginalItemTooltipLang")
                      .HasColumnType("TEXT");

            b.Property<byte[]>("RowVersion")
                      .IsConcurrencyToken()
                      .ValueGeneratedOnAddOrUpdate()
                      .HasColumnType("BLOB");

            b.Property<string>("TranslatedItemTooltip")
                      .HasColumnType("TEXT");

            b.Property<int?>("TranslationEngine")
                      .HasColumnType("INTEGER");

            b.Property<string>("TranslationLang")
                      .HasColumnType("TEXT");

            b.Property<DateTime?>("UpdatedDate")
                      .HasColumnType("TEXT");

            b.HasKey("Id");

            b.ToTable("itemtooltips", (string)null);
          });

      modelBuilder.Entity("EFCoreSqlite.Models.Journal.QuestPlate", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("INTEGER");

            b.Property<DateTime?>("CreatedDate")
                      .HasColumnType("TEXT");

            b.Property<string>("ObjectivesAsText")
                      .HasColumnType("TEXT");

            b.Property<string>("OriginalLang")
                      .HasColumnType("TEXT");

            b.Property<string>("OriginalQuestMessage")
                      .HasColumnType("TEXT");

            b.Property<string>("QuestId")
                      .HasColumnType("TEXT");

            b.Property<string>("QuestName")
                      .HasColumnType("TEXT");

            b.Property<byte[]>("RowVersion")
                      .IsConcurrencyToken()
                      .ValueGeneratedOnAddOrUpdate()
                      .HasColumnType("BLOB");

            b.Property<string>("SummariesAsText")
                      .HasColumnType("TEXT");

            b.Property<string>("TranslatedQuestMessage")
                      .HasColumnType("TEXT");

            b.Property<string>("TranslatedQuestName")
                      .HasColumnType("TEXT");

            b.Property<int?>("TranslationEngine")
                      .HasColumnType("INTEGER");

            b.Property<string>("TranslationLang")
                      .HasColumnType("TEXT");

            b.Property<DateTime?>("UpdatedDate")
                      .HasColumnType("TEXT");

            b.HasKey("Id");

            b.ToTable("questplates", (string)null);
          });

      modelBuilder.Entity("EFCoreSqlite.Models.LocationName", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("INTEGER");

            b.Property<DateTime?>("CreatedDate")
                      .HasColumnType("TEXT");

            b.Property<string>("OriginalLocationName")
                      .HasColumnType("TEXT");

            b.Property<string>("OriginalLocationNameLang")
                      .HasColumnType("TEXT");

            b.Property<byte[]>("RowVersion")
                      .IsConcurrencyToken()
                      .ValueGeneratedOnAddOrUpdate()
                      .HasColumnType("BLOB");

            b.Property<string>("TranslatedLocationName")
                      .HasColumnType("TEXT");

            b.Property<int?>("TranslationEngine")
                      .HasColumnType("INTEGER");

            b.Property<string>("TranslationLang")
                      .HasColumnType("TEXT");

            b.Property<DateTime?>("UpdatedDate")
                      .HasColumnType("TEXT");

            b.HasKey("Id");

            b.ToTable("locationnames", (string)null);
          });

      modelBuilder.Entity("EFCoreSqlite.Models.NpcNames", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("INTEGER");

            b.Property<DateTime?>("CreatedDate")
                      .HasColumnType("TEXT");

            b.Property<string>("OriginalNpcName")
                      .HasColumnType("TEXT");

            b.Property<string>("OriginalNpcNameLang")
                      .HasColumnType("TEXT");

            b.Property<byte[]>("RowVersion")
                      .IsConcurrencyToken()
                      .ValueGeneratedOnAddOrUpdate()
                      .HasColumnType("BLOB");

            b.Property<string>("TranslatedNpcName")
                      .HasColumnType("TEXT");

            b.Property<int?>("TranslationEngine")
                      .HasColumnType("INTEGER");

            b.Property<string>("TranslationLang")
                      .HasColumnType("TEXT");

            b.Property<DateTime?>("UpdatedDate")
                      .HasColumnType("TEXT");

            b.HasKey("Id");

            b.ToTable("npcnames", (string)null);
          });

      modelBuilder.Entity("EFCoreSqlite.Models.SelectString", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("INTEGER");

            b.Property<DateTime?>("CreatedDate")
                      .HasColumnType("TEXT");

            b.Property<string>("OriginalSelectString")
                      .HasColumnType("TEXT");

            b.Property<string>("OriginalSelectStringLang")
                      .HasColumnType("TEXT");

            b.Property<byte[]>("RowVersion")
                      .IsConcurrencyToken()
                      .ValueGeneratedOnAddOrUpdate()
                      .HasColumnType("BLOB");

            b.Property<string>("TranslatedSelectString")
                      .HasColumnType("TEXT");

            b.Property<int?>("TranslationEngine")
                      .HasColumnType("INTEGER");

            b.Property<string>("TranslationLang")
                      .HasColumnType("TEXT");

            b.Property<DateTime?>("UpdatedDate")
                      .HasColumnType("TEXT");

            b.HasKey("Id");

            b.ToTable("selectstrings", (string)null);
          });

      modelBuilder.Entity("EFCoreSqlite.Models.TalkMessage", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("INTEGER");

            b.Property<DateTime?>("CreatedDate")
                      .HasColumnType("TEXT");

            b.Property<string>("OriginalSenderNameLang")
                      .HasColumnType("TEXT");

            b.Property<string>("OriginalTalkMessage")
                      .HasColumnType("TEXT");

            b.Property<string>("OriginalTalkMessageLang")
                      .HasColumnType("TEXT");

            b.Property<byte[]>("RowVersion")
                      .IsConcurrencyToken()
                      .ValueGeneratedOnAddOrUpdate()
                      .HasColumnType("BLOB");

            b.Property<string>("SenderName")
                      .HasColumnType("TEXT");

            b.Property<string>("TranslatedSenderName")
                      .HasColumnType("TEXT");

            b.Property<string>("TranslatedTalkMessage")
                      .HasColumnType("TEXT");

            b.Property<int?>("TranslationEngine")
                      .HasColumnType("INTEGER");

            b.Property<string>("TranslationLang")
                      .HasColumnType("TEXT");

            b.Property<DateTime?>("UpdatedDate")
                      .HasColumnType("TEXT");

            b.HasKey("Id");

            b.ToTable("talkmessages", (string)null);
          });

      modelBuilder.Entity("EFCoreSqlite.Models.TalkSubtitleMessage", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("INTEGER");

            b.Property<DateTime?>("CreatedDate")
                      .HasColumnType("TEXT");

            b.Property<string>("OriginalTalkSubtitleMessage")
                      .HasColumnType("TEXT");

            b.Property<string>("OriginalTalkSubtitleMessageLang")
                      .HasColumnType("TEXT");

            b.Property<byte[]>("RowVersion")
                      .IsConcurrencyToken()
                      .ValueGeneratedOnAddOrUpdate()
                      .HasColumnType("BLOB");

            b.Property<string>("TranslatedTalkSubtitleMessage")
                      .HasColumnType("TEXT");

            b.Property<int?>("TranslationEngine")
                      .HasColumnType("INTEGER");

            b.Property<string>("TranslationLang")
                      .HasColumnType("TEXT");

            b.Property<DateTime?>("UpdatedDate")
                      .HasColumnType("TEXT");

            b.HasKey("Id");

            b.ToTable("talksubtitlemessages", (string)null);
          });

      modelBuilder.Entity("EFCoreSqlite.Models.ToastMessage", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("INTEGER");

            b.Property<DateTime?>("CreatedDate")
                      .HasColumnType("TEXT");

            b.Property<string>("OriginalLang")
                      .HasColumnType("TEXT");

            b.Property<string>("OriginalToastMessage")
                      .HasColumnType("TEXT");

            b.Property<byte[]>("RowVersion")
                      .IsConcurrencyToken()
                      .ValueGeneratedOnAddOrUpdate()
                      .HasColumnType("BLOB");

            b.Property<string>("ToastType")
                      .HasColumnType("TEXT");

            b.Property<string>("TranslatedToastMessage")
                      .HasColumnType("TEXT");

            b.Property<int?>("TranslationEngine")
                      .HasColumnType("INTEGER");

            b.Property<string>("TranslationLang")
                      .HasColumnType("TEXT");

            b.Property<DateTime?>("UpdatedDate")
                      .HasColumnType("TEXT");

            b.HasKey("Id");

            b.ToTable("toastmessages", (string)null);
          });
#pragma warning restore 612, 618
    }
  }
}
