// <auto-generated />
using System;
using Echoglossian.EFCoreSqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Echoglossian.EFCoreSqlite.Migrations
{
    [DbContext(typeof(EchoglossianDbContext))]
    [Migration("20260425222450_AddReferenceTextTables")]
    partial class AddReferenceTextTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.ActionTooltip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ActionCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionDescription")
                        .HasColumnType("TEXT");

                    b.Property<uint>("ActionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalPayloadAsText")
                        .HasColumnType("TEXT");

                    b.Property<uint>("ClassJobCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ClassJobId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameVersion")
                        .HasColumnType("TEXT");

                    b.Property<uint>("IconId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalLang")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTooltipText")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("SourceContentHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedActionDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedActionName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedTooltipText")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActionId", "TranslationLang", "TranslationEngine", "GameVersion", "SourceContentHash")
                        .HasDatabaseName("IX_actiontooltips_lookup");

                    b.ToTable("actiontooltips", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.AozActionText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalPayloadAsText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLang")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalName")
                        .HasColumnType("TEXT");

                    b.Property<uint>("ReferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("SourceContentHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceId", "TranslationLang", "TranslationEngine", "GameVersion", "SourceContentHash")
                        .HasDatabaseName("IX_aozactiontexts_lookup");

                    b.ToTable("aozactiontexts", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.BattleTalkMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalBattleTalkMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalBattleTalkMessageLang")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalSenderNameLang")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RTLLangTranslationImageData")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("SenderName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedBattleTalkMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedSenderName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SenderName", "TranslationLang", "TranslationEngine")
                        .HasDatabaseName("IX_battletalkmessages_lookup");

                    b.ToTable("battletalkmessages", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.BgcArmyActionText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalPayloadAsText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLang")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalName")
                        .HasColumnType("TEXT");

                    b.Property<uint>("ReferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("SourceContentHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceId", "TranslationLang", "TranslationEngine", "GameVersion", "SourceContentHash")
                        .HasDatabaseName("IX_bgcarmyactiontexts_lookup");

                    b.ToTable("bgcarmyactiontexts", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.BuddyActionText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalPayloadAsText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLang")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalName")
                        .HasColumnType("TEXT");

                    b.Property<uint>("ReferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("SourceContentHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceId", "TranslationLang", "TranslationEngine", "GameVersion", "SourceContentHash")
                        .HasDatabaseName("IX_buddyactiontexts_lookup");

                    b.ToTable("buddyactiontexts", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.CompanyActionText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalPayloadAsText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLang")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalName")
                        .HasColumnType("TEXT");

                    b.Property<uint>("ReferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("SourceContentHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceId", "TranslationLang", "TranslationEngine", "GameVersion", "SourceContentHash")
                        .HasDatabaseName("IX_companyactiontexts_lookup");

                    b.ToTable("companyactiontexts", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.CraftActionText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalPayloadAsText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLang")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalName")
                        .HasColumnType("TEXT");

                    b.Property<uint>("ReferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("SourceContentHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceId", "TranslationLang", "TranslationEngine", "GameVersion", "SourceContentHash")
                        .HasDatabaseName("IX_craftactiontexts_lookup");

                    b.ToTable("craftactiontexts", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.EurekaMagiaActionText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalPayloadAsText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLang")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalName")
                        .HasColumnType("TEXT");

                    b.Property<uint>("ReferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("SourceContentHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceId", "TranslationLang", "TranslationEngine", "GameVersion", "SourceContentHash")
                        .HasDatabaseName("IX_eurekamagiaactiontexts_lookup");

                    b.ToTable("eurekamagiaactiontexts", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.EventActionText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalPayloadAsText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLang")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalName")
                        .HasColumnType("TEXT");

                    b.Property<uint>("ReferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("SourceContentHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceId", "TranslationLang", "TranslationEngine", "GameVersion", "SourceContentHash")
                        .HasDatabaseName("IX_eventactiontexts_lookup");

                    b.ToTable("eventactiontexts", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.GameWindow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("ClassJobId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalWindowStrings")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalWindowStringsLang")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("TranslatedWindowStrings")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("WindowAddonName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WindowAddonName", "TranslationLang", "TranslationEngine", "GameVersion")
                        .HasDatabaseName("IX_gamewindows_lookup");

                    b.HasIndex("WindowAddonName", "ClassJobId", "TranslationLang", "TranslationEngine", "GameVersion")
                        .HasDatabaseName("IX_gamewindows_classjob_lookup");

                    b.ToTable("gamewindows", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.GeneralActionText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalPayloadAsText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLang")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalName")
                        .HasColumnType("TEXT");

                    b.Property<uint>("ReferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("SourceContentHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceId", "TranslationLang", "TranslationEngine", "GameVersion", "SourceContentHash")
                        .HasDatabaseName("IX_generalactiontexts_lookup");

                    b.ToTable("generalactiontexts", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.ItemTooltip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalPayloadAsText")
                        .HasColumnType("TEXT");

                    b.Property<uint>("ClassJobCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameVersion")
                        .HasColumnType("TEXT");

                    b.Property<uint>("IconId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ItemActionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("TEXT");

                    b.Property<uint>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .HasColumnType("TEXT");

                    b.Property<uint>("ItemUiCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalLang")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTooltipText")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("SourceContentHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedItemDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedItemName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedTooltipText")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId", "TranslationLang", "TranslationEngine", "GameVersion", "SourceContentHash")
                        .HasDatabaseName("IX_itemtooltips_lookup");

                    b.ToTable("itemtooltips", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.Journal.QuestPlate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalRowsAsText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectiveRowsByKeyAsText")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectivesAsText")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLang")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalQuestMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestName")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestTextSheetName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceContentHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("SummariesAsText")
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryRowsByKeyAsText")
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemRowsAsText")
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemRowsByKeyAsText")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedObjectiveRowsByKeyAsText")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedObjectivesAsText")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedQuestMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedQuestName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedSummariesAsText")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedSummaryRowsByKeyAsText")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedSystemRowsAsText")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedSystemRowsByKeyAsText")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuestId", "TranslationLang", "TranslationEngine", "GameVersion")
                        .HasDatabaseName("IX_questplates_questid_lookup");

                    b.HasIndex("QuestName", "TranslationLang", "TranslationEngine", "GameVersion")
                        .HasDatabaseName("IX_questplates_lookup");

                    b.ToTable("questplates", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.LocationName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLocationName")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLocationNameLang")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("TranslatedLocationName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("locationnames", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.MiniTalkMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalMiniTalkMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalMiniTalkMessageLang")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("TranslatedMiniTalkMessage")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TranslationLang", "TranslationEngine")
                        .HasDatabaseName("IX_minitalkmessages_lookup");

                    b.ToTable("minitalkmessages", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.MountActionText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalPayloadAsText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLang")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalName")
                        .HasColumnType("TEXT");

                    b.Property<uint>("ReferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("SourceContentHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceId", "TranslationLang", "TranslationEngine", "GameVersion", "SourceContentHash")
                        .HasDatabaseName("IX_mountactiontexts_lookup");

                    b.ToTable("mountactiontexts", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.NpcNames", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalNpcName")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalNpcNameLang")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("TranslatedNpcName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("npcnames", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.PetActionText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalPayloadAsText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLang")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalName")
                        .HasColumnType("TEXT");

                    b.Property<uint>("ReferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("SourceContentHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceId", "TranslationLang", "TranslationEngine", "GameVersion", "SourceContentHash")
                        .HasDatabaseName("IX_petactiontexts_lookup");

                    b.ToTable("petactiontexts", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.PvPActionText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalPayloadAsText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLang")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalName")
                        .HasColumnType("TEXT");

                    b.Property<uint>("ReferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("SourceContentHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceId", "TranslationLang", "TranslationEngine", "GameVersion", "SourceContentHash")
                        .HasDatabaseName("IX_pvpactiontexts_lookup");

                    b.ToTable("pvpactiontexts", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.SelectString", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalOptionsAsText")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalSelectString")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalSelectStringLang")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("TranslatedOptionsAsText")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedSelectString")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OriginalSelectString", "OriginalOptionsAsText", "TranslationLang", "TranslationEngine")
                        .HasDatabaseName("IX_selectstrings_lookup");

                    b.ToTable("selectstrings", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.StringArrayDatas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContextKey")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormattedRawData")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLang")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalStrings")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalStructuredPayload")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RawData")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<int?>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceContentHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedStrings")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedStringsWithPayloads")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedStructuredPayload")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Type", "TranslationLang", "TranslationEngine")
                        .HasDatabaseName("IX_stringarraydatas_lookup");

                    b.HasIndex("Type", "ContextKey", "TranslationLang", "TranslationEngine", "GameVersion", "SourceContentHash")
                        .HasDatabaseName("IX_stringarraydatas_context_lookup");

                    b.ToTable("stringarraydatas");
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.TalkMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalSenderNameLang")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTalkMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTalkMessageLang")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RTLLangTranslationImageData")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("SenderName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedSenderName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedTalkMessage")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SenderName", "TranslationLang", "TranslationEngine")
                        .HasDatabaseName("IX_talkmessages_lookup");

                    b.ToTable("talkmessages", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.TalkSubtitleMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTalkSubtitleMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTalkSubtitleMessageLang")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("TranslatedTalkSubtitleMessage")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TranslationLang", "TranslationEngine")
                        .HasDatabaseName("IX_talksubtitlemessages_lookup");

                    b.ToTable("talksubtitlemessages", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.TextGimmickHintMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLang")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalText")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("TranslatedText")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TranslationLang", "TranslationEngine")
                        .HasDatabaseName("IX_textgimmickhintmessages_lookup");

                    b.ToTable("textgimmickhintmessages", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.ToastMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLang")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalToastMessage")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("ToastType")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedToastMessage")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ToastType", "TranslationLang", "TranslationEngine")
                        .HasDatabaseName("IX_toastmessages_lookup");

                    b.ToTable("toastmessages", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.Trait", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalPayloadAsText")
                        .HasColumnType("TEXT");

                    b.Property<uint>("ClassJobCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ClassJobId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameVersion")
                        .HasColumnType("TEXT");

                    b.Property<uint>("IconId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalLang")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTooltipText")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("SourceContentHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("TraitDescription")
                        .HasColumnType("TEXT");

                    b.Property<uint>("TraitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TraitName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedTooltipText")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedTraitDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedTraitName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TraitId", "TranslationLang", "TranslationEngine", "GameVersion", "SourceContentHash")
                        .HasDatabaseName("IX_traits_lookup");

                    b.ToTable("Traits", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.TranslationFailure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailureCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstSeenOrigin")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSeenOrigin")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("SourceLanguage")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceText")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceTextHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetLanguage")
                        .HasColumnType("TEXT");

                    b.Property<int>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceTextHash", "SourceLanguage", "TargetLanguage", "TranslationEngine", "SourceText")
                        .IsUnique()
                        .HasDatabaseName("IX_translationfailures_lookup");

                    b.ToTable("translationfailures", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
