// <auto-generated />
using System;
using Echoglossian.EFCoreSqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Echoglossian.EFCoreSqlite.Migrations
{
    [DbContext(typeof(EchoglossianDbContext))]
    partial class EchoglossianDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.ActionTooltip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalActionTooltip")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalActionTooltipLang")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("TranslatedActionTooltip")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("actiontooltips", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.BattleTalkMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalBattleTalkMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalBattleTalkMessageLang")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalSenderNameLang")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RTLLangTranslationImageData")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("SenderName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedBattleTalkMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedSenderName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SenderName", "TranslationLang", "TranslationEngine")
                        .HasDatabaseName("IX_battletalkmessages_lookup");

                    b.ToTable("battletalkmessages", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.GameWindow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalWindowStrings")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalWindowStringsLang")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("TranslatedWindowStrings")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("WindowAddonName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WindowAddonName", "TranslationLang", "TranslationEngine", "GameVersion")
                        .HasDatabaseName("IX_gamewindows_lookup");

                    b.ToTable("gamewindows", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.ItemTooltip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalItemTooltip")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalItemTooltipLang")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("TranslatedItemTooltip")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("itemtooltips", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.Journal.QuestPlate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectivesAsText")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLang")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalQuestMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestId")
                        .HasColumnType("TEXT");

            b.Property<string>("QuestName")
                .HasColumnType("TEXT");

            b.Property<string>("QuestTextSheetName")
                .HasColumnType("TEXT");

                    b.Property<string>("SourceContentHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("SummariesAsText")
                .HasColumnType("TEXT");

                    b.Property<string>("SystemRowsAsText")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedObjectivesAsText")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedSummariesAsText")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedSystemRowsAsText")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedQuestMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedQuestName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuestName", "TranslationLang", "TranslationEngine", "GameVersion")
                        .HasDatabaseName("IX_questplates_lookup");

                    b.HasIndex("QuestId", "TranslationLang", "TranslationEngine", "GameVersion")
                        .HasDatabaseName("IX_questplates_questid_lookup");

                    b.ToTable("questplates", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.LocationName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLocationName")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLocationNameLang")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("TranslatedLocationName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("locationnames", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.NpcNames", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalNpcName")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalNpcNameLang")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("TranslatedNpcName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("npcnames", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.SelectString", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalSelectString")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalSelectStringLang")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalOptionsAsText")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("TranslatedOptionsAsText")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedSelectString")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OriginalSelectString", "OriginalOptionsAsText", "TranslationLang", "TranslationEngine")
                        .HasDatabaseName("IX_selectstrings_lookup");

                    b.ToTable("selectstrings", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.StringArrayDatas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormattedRawData")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLang")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalStrings")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RawData")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslatedStrings")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedStringsWithPayloads")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Type", "TranslationLang", "TranslationEngine")
                        .HasDatabaseName("IX_stringarraydatas_lookup");

                    b.ToTable("stringarraydatas");
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.TalkMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalSenderNameLang")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTalkMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTalkMessageLang")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RTLLangTranslationImageData")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("SenderName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedSenderName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedTalkMessage")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SenderName", "TranslationLang", "TranslationEngine")
                        .HasDatabaseName("IX_talkmessages_lookup");

                    b.ToTable("talkmessages", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.TalkSubtitleMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTalkSubtitleMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTalkSubtitleMessageLang")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("TranslatedTalkSubtitleMessage")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TranslationLang", "TranslationEngine")
                        .HasDatabaseName("IX_talksubtitlemessages_lookup");

                    b.ToTable("talksubtitlemessages", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.MiniTalkMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalMiniTalkMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalMiniTalkMessageLang")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("TranslatedMiniTalkMessage")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TranslationLang", "TranslationEngine")
                        .HasDatabaseName("IX_minitalkmessages_lookup");

                    b.ToTable("minitalkmessages", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.TextGimmickHintMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLang")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalText")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("TranslatedText")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TranslationLang", "TranslationEngine")
                        .HasDatabaseName("IX_textgimmickhintmessages_lookup");

                    b.ToTable("textgimmickhintmessages", (string)null);
                });

            modelBuilder.Entity("Echoglossian.EFCoreSqlite.Models.ToastMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLang")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalToastMessage")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("ToastType")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedToastMessage")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TranslationEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationLang")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ToastType", "TranslationLang", "TranslationEngine")
                        .HasDatabaseName("IX_toastmessages_lookup");

                    b.ToTable("toastmessages", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
