<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Use_DalamudPackager>false</Use_DalamudPackager>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup Label="Needed as we require the Dalamud DLLs in the output directory.">
    <Reference Include="Dalamud">
      <HintPath>$(DalamudLibPath)Dalamud.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Dalamud.Bindings.ImGui">
      <HintPath>$(DalamudLibPath)Dalamud.Bindings.ImGui.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Dalamud.Bindings.ImGuizmo">
      <HintPath>$(DalamudLibPath)Dalamud.Bindings.ImGuizmo.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Dalamud.Bindings.ImPlot">
      <HintPath>$(DalamudLibPath)Dalamud.Bindings.ImPlot.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="ImGuiScene">
      <HintPath>$(DalamudLibPath)ImGuiScene.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Lumina">
      <HintPath>$(DalamudLibPath)Lumina.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Lumina.Excel">
      <HintPath>$(DalamudLibPath)Lumina.Excel.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="FFXIVClientStructs">
      <HintPath>$(DalamudLibPath)FFXIVClientStructs.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json" PrivateAssets="All">
      <HintPath>$(DalamudLibPath)Newtonsoft.Json.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="StbiSharp">
      <HintPath>$(DalamudLibPath)StbiSharp.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="InteropGenerator.Runtime">
      <HintPath>$(DalamudLibPath)InteropGenerator.Runtime.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\\Echoglossian.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\\vendor\\DalaMock\\DalaMock\\DalaMock.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="DotNet.ReproducibleBuilds" Version="2.0.5" />
  </ItemGroup>
</Project>
